const keyboard = [
  [
    { text: 'Afrikaans', callback_data: 'af' },
    { text: 'Albanian', callback_data: 'sq' },
    { text: 'Amharic', callback_data: 'am' },
    { text: 'Arabic', callback_data: 'ar' },
  ],
  [
    { text: 'Armenian', callback_data: 'hy' },
    { text: 'Azerbaijani', callback_data: 'az' },
    { text: 'Basque', callback_data: 'eu' },
    { text: 'Belarusian', callback_data: 'be' },
  ],
  [
    { text: 'Bengali', callback_data: 'bn' },
    { text: 'Bosnian', callback_data: 'bs' },
    { text: 'Bulgarian', callback_data: 'bg' },
    { text: 'Catalan', callback_data: 'ca' },
  ],
  [
    { text: 'Cebuano', callback_data: 'ceb' },
    { text: 'Chichewa', callback_data: 'ny' },
    { text: 'Chinese (Simplified)', callback_data: 'zh-CN' },
    { text: 'Chinese (Traditional)', callback_data: 'zh-TW' },
  ],
  [
    { text: 'Corsican', callback_data: 'co' },
    { text: 'Croatian', callback_data: 'hr' },
    { text: 'Czech', callback_data: 'cs' },
    { text: 'Danish', callback_data: 'da' },
  ],
  [
    { text: 'Dutch', callback_data: 'nl' },
    { text: 'English', callback_data: 'en' },
    { text: 'Esperanto', callback_data: 'eo' },
    { text: 'Estonian', callback_data: 'et' },
  ],
  [
    { text: 'Filipino', callback_data: 'tl' },
    { text: 'Finnish', callback_data: 'fi' },
    { text: 'French', callback_data: 'fr' },
    { text: 'Frisian', callback_data: 'fy' },
  ],
  [
    { text: 'Galician', callback_data: 'gl' },
    { text: 'German', callback_data: 'de' },
    { text: 'Greek', callback_data: 'el' },
    { text: 'Gujarati', callback_data: 'gu' },
  ],
  [
    { text: 'Haitian Creole', callback_data: 'ht' },
    { text: 'Hausa', callback_data: 'ha' },
    { text: 'Hawaiian', callback_data: 'haw' },
    { text: 'Hebrew', callback_data: 'iw' },
  ],
  [
    { text: 'Hindi', callback_data: 'hi' },
    { text: 'Hmong', callback_data: 'hmn' },
    { text: 'Hungarian', callback_data: 'hu' },
    { text: 'Icelandic', callback_data: 'is' },
  ],
  [
    { text: 'Igbo', callback_data: 'ig' },
    { text: 'Indonesian', callback_data: 'id' },
    { text: 'Irish', callback_data: 'ga' },
    { text: 'Italian', callback_data: 'it' },
  ],
  [
    { text: 'Japanese', callback_data: 'ja' },
    { text: 'Javanese', callback_data: 'jw' },
    { text: 'Kannada', callback_data: 'kn' },
    { text: 'Kazakh', callback_data: 'kk' },
  ],
  [
    { text: 'Khmer', callback_data: 'km' },
    { text: 'Kinyarwanda', callback_data: 'rw' },
    { text: 'Korean', callback_data: 'ko' },
    { text: 'Kurdish (Kurmanji)', callback_data: 'ku' },
  ],
  [
    { text: 'Kyrgyz', callback_data: 'ky' },
    { text: 'Lao', callback_data: 'lo' },
    { text: 'Latin', callback_data: 'la' },
    { text: 'Latvian', callback_data: 'lv' },
  ],
  [
    { text: 'Lithuanian', callback_data: 'lt' },
    { text: 'Luxembourgish', callback_data: 'lb' },
    { text: 'Macedonian', callback_data: 'mk' },
    { text: 'Malagasy', callback_data: 'mg' },
  ],
  [
    { text: 'Malay', callback_data: 'ms' },
    { text: 'Malayalam', callback_data: 'ml' },
    { text: 'Maltese', callback_data: 'mt' },
    { text: 'Maori', callback_data: 'mi' },
  ],
  [
    { text: 'Marathi', callback_data: 'mr' },
    { text: 'Mongolian', callback_data: 'mn' },
    { text: 'Myanmar (Burmese)', callback_data: 'my' },
    { text: 'Nepali', callback_data: 'ne' },
  ],
  [
    { text: 'Norwegian', callback_data: 'no' },
    { text: 'Odia (Oriya)', callback_data: 'or' },
    { text: 'Pashto', callback_data: 'ps' },
    { text: 'Persian', callback_data: 'fa' },
  ],
  [
    { text: 'Polish', callback_data: 'pl' },
    { text: 'Portuguese', callback_data: 'pt' },
    { text: 'Punjabi', callback_data: 'pa' },
    { text: 'Romanian', callback_data: 'ro' },
  ],
  [
    { text: 'Russian', callback_data: 'ru' },
    { text: 'Samoan', callback_data: 'sm' },
    { text: 'Scots Gaelic', callback_data: 'gd' },
    { text: 'Serbian', callback_data: 'sr' },
  ],
  [
    { text: 'Sesotho', callback_data: 'st' },
    { text: 'Shona', callback_data: 'sn' },
    { text: 'Sindhi', callback_data: 'sd' },
    { text: 'Sinhala', callback_data: 'si' },
  ],
  [
    { text: 'Slovak', callback_data: 'sk' },
    { text: 'Slovenian', callback_data: 'sl' },
    { text: 'Somali', callback_data: 'so' },
    { text: 'Spanish', callback_data: 'es' },
  ],
  [
    { text: 'Sundanese', callback_data: 'su' },
    { text: 'Swahili', callback_data: 'sw' },
    { text: 'Swedish', callback_data: 'sv' },
    { text: 'Tajik', callback_data: 'tg' },
  ],
  [
    { text: 'Tamil', callback_data: 'ta' },
    { text: 'Tatar', callback_data: 'tt' },
    { text: 'Telugu', callback_data: 'te' },
    { text: 'Thai', callback_data: 'th' },
  ],
  [
    { text: 'Turkish', callback_data: 'tr' },
    { text: 'Turkmen', callback_data: 'tk' },
    { text: 'Ukrainian', callback_data: 'uk' },
    { text: 'Urdu', callback_data: 'ur' },
  ],
  [
    { text: 'Uyghur', callback_data: 'ug' },
    { text: 'Uzbek', callback_data: 'uz' },
    { text: 'Vietnamese', callback_data: 'vi' },
    { text: 'Welsh', callback_data: 'cy' },
  ],
  [
    { text: 'Xhosa', callback_data: 'xh' },
    { text: 'Yiddish', callback_data: 'yi' },
    { text: 'Yoruba', callback_data: 'yo' },
    { text: 'Zulu', callback_data: 'zu' },
  ],
  [
    { text: 'Hebrew', callback_data: 'he' },
    { text: 'Chinese (Simplified)', callback_data: 'zh' },
  ],
];

module.exports = keyboard;
