function getTransliterated(str) {
  return str
    .replace(/k'/gi, 'კ')
    .replace(/ts'/gi, 'წ')
    .replace(/p'/gi, 'პ')
    .replace(/t'/gi, 'ტ')
    .replace(/ch'/gi, 'ჭ')
    .replace(/ch/gi, 'ჩ')
    .replace(/zh/gi, 'ჟ')
    .replace(/gh/gi, 'ღ')
    .replace(/sh/gi, 'შ')
    .replace(/dz/gi, 'ძ')
    .replace(/(kh)|(x)/gi, 'ხ')
    .replace(/(ts)|(c)/gi, 'ც')
    .replace(/t/gi, 'თ')
    .replace(/h/gi, 'ჰ')
    .replace(/d/gi, 'დ')
    .replace(/z/gi, 'ზ')
    .replace(/k/gi, 'ქ')
    .replace(/s/gi, 'ს')
    .replace(/(p)|(f)/gi, 'ფ')
    .replace(/(v)|(w)/gi, 'ვ')
    .replace(/a/gi, 'ა')
    .replace(/b/gi, 'ბ')
    .replace(/g/gi, 'გ')
    .replace(/e/gi, 'ე')
    .replace(/i/gi, 'ი')
    .replace(/l/gi, 'ლ')
    .replace(/m/gi, 'მ')
    .replace(/n/gi, 'ნ')
    .replace(/o/gi, 'ო')
    .replace(/r/gi, 'რ')
    .replace(/u/gi, 'უ')
    .replace(/q/gi, 'ყ')
    .replace(/j/gi, 'ჯ');
}

module.exports = getTransliterated;
